stages:
  download_data:
    cmd: cp ../data/shared_data.xml data/data.xml
    deps:
    - ../data/shared_data.xml
    outs:
    - data/data.xml

  train:
    cmd: python train.py
    deps:
    - data/data.xml
    params:
    - params.yaml:
    metrics:
    - dvclive/metrics.json:
        cache: false
    plots:
    - dvclive/plots:
        cache: false

metrics:
- dvclive/metrics.json
plots:
- dvclive/plots/metrics:
    x: step
